# config context path to "/" by setting an empty string
server:
  contextPath:
# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://localhost:3306/wafaa?autoReconnect=true&useSSL=false
    username: root
    password: wafaa
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none 
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
#logging:
#  level:
#    org.springframework:
#      security: DEBUG

